# Dockerfile-flask# We simply inherit the Python 3 image. This image does
# not particularly care what OS runs underneath

FROM python:3

# Set an environment variable with the directory
# where we'll be running the app
ENV APP /app

# Create the directory and instruct Docker to operate
# from there from now on
RUN mkdir $APP
WORKDIR $APP

EXPOSE 5092

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY main.py .
COPY api /app/api

CMD [ "python", "./main.py" ]
